name: Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Uses .luacheckrc for the WoW globals.
      - uses: lunarmodules/luacheck@v1
        with:
          args: FadeUI
